#!/usr/bin/env bash

set -exuo pipefail

# Install golangci-lint
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "${GOPATH}/bin" v1.42.0

# addlicense tool.
go install github.com/google/addlicense@v1.0.0
