#!/usr/bin/env bash

set -euo pipefail

# golangci-lint
args=()
if [[ "${GITHUB_ACTIONS:-false}" == "true" ]]; then
    args+=("--out-format" "github-actions")
fi

golangci-lint run "${args[@]}"

# License check.
find . -name '*.go' | xargs addlicense -check
