name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "33 11 * * 6"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-20.04]
        tags: ["", "purego"]
    runs-on: ${{ matrix.platform }}
    env:
      GOFLAGS: "-tags=${{ matrix.tags }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Build
        run: go build
      - name: Test
        run: go test -v -bench . -benchtime=1x
      - name: Comparison Tests
        working-directory: internal/tests
        run: go test -v -bench . -benchtime=1x

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: 1.20.x
      - name: Configure Go Environment
        run: |
          echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
          echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Lint
        run: ./script/lint
      - name: Generate
        run: ./script/generate
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
